name = "dcc"
compatibility_date = "2024-01-22"
# account_id = ""

kv_namespaces = [
  { binding = "KV", id = "dev" }
]

[[d1_databases]]
binding = "DB"
database_name = "dcc"
database_id = "5dccae67-7b68-4613-a7c5-5294e5256727"